version = 1

exclude_patterns = [
  "internal/ent/*",
  "internal/graphql/*",
  "ui/$houdini",
  "ui/.svelte-kit"
]

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/responserms/response"

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[transformers]]
name = "gofmt"
enabled = true

[[transformers]]
name = "prettier"
enabled = true