// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/responserms/response/internal/ent/gameserver"
	"github.com/responserms/response/internal/ent/metadata"
	"github.com/responserms/response/internal/ent/player"
	"github.com/responserms/response/internal/ent/predicate"
)

// GameServerQuery is the builder for querying GameServer entities.
type GameServerQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.GameServer
	// eager-loading edges.
	withMetadata *MetadataQuery
	withPlayers  *PlayerQuery
	withFKs      bool
	modifiers    []func(s *sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GameServerQuery builder.
func (gsq *GameServerQuery) Where(ps ...predicate.GameServer) *GameServerQuery {
	gsq.predicates = append(gsq.predicates, ps...)
	return gsq
}

// Limit adds a limit step to the query.
func (gsq *GameServerQuery) Limit(limit int) *GameServerQuery {
	gsq.limit = &limit
	return gsq
}

// Offset adds an offset step to the query.
func (gsq *GameServerQuery) Offset(offset int) *GameServerQuery {
	gsq.offset = &offset
	return gsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (gsq *GameServerQuery) Unique(unique bool) *GameServerQuery {
	gsq.unique = &unique
	return gsq
}

// Order adds an order step to the query.
func (gsq *GameServerQuery) Order(o ...OrderFunc) *GameServerQuery {
	gsq.order = append(gsq.order, o...)
	return gsq
}

// QueryMetadata chains the current query on the "metadata" edge.
func (gsq *GameServerQuery) QueryMetadata() *MetadataQuery {
	query := &MetadataQuery{config: gsq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := gsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := gsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(gameserver.Table, gameserver.FieldID, selector),
			sqlgraph.To(metadata.Table, metadata.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, gameserver.MetadataTable, gameserver.MetadataColumn),
		)
		fromU = sqlgraph.SetNeighbors(gsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPlayers chains the current query on the "players" edge.
func (gsq *GameServerQuery) QueryPlayers() *PlayerQuery {
	query := &PlayerQuery{config: gsq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := gsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := gsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(gameserver.Table, gameserver.FieldID, selector),
			sqlgraph.To(player.Table, player.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, gameserver.PlayersTable, gameserver.PlayersPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(gsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first GameServer entity from the query.
// Returns a *NotFoundError when no GameServer was found.
func (gsq *GameServerQuery) First(ctx context.Context) (*GameServer, error) {
	nodes, err := gsq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{gameserver.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (gsq *GameServerQuery) FirstX(ctx context.Context) *GameServer {
	node, err := gsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GameServer ID from the query.
// Returns a *NotFoundError when no GameServer ID was found.
func (gsq *GameServerQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = gsq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{gameserver.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (gsq *GameServerQuery) FirstIDX(ctx context.Context) int {
	id, err := gsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GameServer entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one GameServer entity is not found.
// Returns a *NotFoundError when no GameServer entities are found.
func (gsq *GameServerQuery) Only(ctx context.Context) (*GameServer, error) {
	nodes, err := gsq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{gameserver.Label}
	default:
		return nil, &NotSingularError{gameserver.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (gsq *GameServerQuery) OnlyX(ctx context.Context) *GameServer {
	node, err := gsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GameServer ID in the query.
// Returns a *NotSingularError when exactly one GameServer ID is not found.
// Returns a *NotFoundError when no entities are found.
func (gsq *GameServerQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = gsq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{gameserver.Label}
	default:
		err = &NotSingularError{gameserver.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (gsq *GameServerQuery) OnlyIDX(ctx context.Context) int {
	id, err := gsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GameServers.
func (gsq *GameServerQuery) All(ctx context.Context) ([]*GameServer, error) {
	if err := gsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return gsq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (gsq *GameServerQuery) AllX(ctx context.Context) []*GameServer {
	nodes, err := gsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GameServer IDs.
func (gsq *GameServerQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := gsq.Select(gameserver.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (gsq *GameServerQuery) IDsX(ctx context.Context) []int {
	ids, err := gsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (gsq *GameServerQuery) Count(ctx context.Context) (int, error) {
	if err := gsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return gsq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (gsq *GameServerQuery) CountX(ctx context.Context) int {
	count, err := gsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (gsq *GameServerQuery) Exist(ctx context.Context) (bool, error) {
	if err := gsq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return gsq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (gsq *GameServerQuery) ExistX(ctx context.Context) bool {
	exist, err := gsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GameServerQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (gsq *GameServerQuery) Clone() *GameServerQuery {
	if gsq == nil {
		return nil
	}
	return &GameServerQuery{
		config:       gsq.config,
		limit:        gsq.limit,
		offset:       gsq.offset,
		order:        append([]OrderFunc{}, gsq.order...),
		predicates:   append([]predicate.GameServer{}, gsq.predicates...),
		withMetadata: gsq.withMetadata.Clone(),
		withPlayers:  gsq.withPlayers.Clone(),
		// clone intermediate query.
		sql:  gsq.sql.Clone(),
		path: gsq.path,
	}
}

// WithMetadata tells the query-builder to eager-load the nodes that are connected to
// the "metadata" edge. The optional arguments are used to configure the query builder of the edge.
func (gsq *GameServerQuery) WithMetadata(opts ...func(*MetadataQuery)) *GameServerQuery {
	query := &MetadataQuery{config: gsq.config}
	for _, opt := range opts {
		opt(query)
	}
	gsq.withMetadata = query
	return gsq
}

// WithPlayers tells the query-builder to eager-load the nodes that are connected to
// the "players" edge. The optional arguments are used to configure the query builder of the edge.
func (gsq *GameServerQuery) WithPlayers(opts ...func(*PlayerQuery)) *GameServerQuery {
	query := &PlayerQuery{config: gsq.config}
	for _, opt := range opts {
		opt(query)
	}
	gsq.withPlayers = query
	return gsq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GameServer.Query().
//		GroupBy(gameserver.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (gsq *GameServerQuery) GroupBy(field string, fields ...string) *GameServerGroupBy {
	group := &GameServerGroupBy{config: gsq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := gsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return gsq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.GameServer.Query().
//		Select(gameserver.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (gsq *GameServerQuery) Select(fields ...string) *GameServerSelect {
	gsq.fields = append(gsq.fields, fields...)
	return &GameServerSelect{GameServerQuery: gsq}
}

func (gsq *GameServerQuery) prepareQuery(ctx context.Context) error {
	for _, f := range gsq.fields {
		if !gameserver.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if gsq.path != nil {
		prev, err := gsq.path(ctx)
		if err != nil {
			return err
		}
		gsq.sql = prev
	}
	return nil
}

func (gsq *GameServerQuery) sqlAll(ctx context.Context) ([]*GameServer, error) {
	var (
		nodes       = []*GameServer{}
		withFKs     = gsq.withFKs
		_spec       = gsq.querySpec()
		loadedTypes = [2]bool{
			gsq.withMetadata != nil,
			gsq.withPlayers != nil,
		}
	)
	if gsq.withMetadata != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, gameserver.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &GameServer{config: gsq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(gsq.modifiers) > 0 {
		_spec.Modifiers = gsq.modifiers
	}
	if err := sqlgraph.QueryNodes(ctx, gsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := gsq.withMetadata; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*GameServer)
		for i := range nodes {
			if nodes[i].game_server_metadata == nil {
				continue
			}
			fk := *nodes[i].game_server_metadata
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(metadata.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "game_server_metadata" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Metadata = n
			}
		}
	}

	if query := gsq.withPlayers; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		ids := make(map[int]*GameServer, len(nodes))
		for _, node := range nodes {
			ids[node.ID] = node
			fks = append(fks, node.ID)
			node.Edges.Players = []*Player{}
		}
		var (
			edgeids []int
			edges   = make(map[int][]*GameServer)
		)
		_spec := &sqlgraph.EdgeQuerySpec{
			Edge: &sqlgraph.EdgeSpec{
				Inverse: true,
				Table:   gameserver.PlayersTable,
				Columns: gameserver.PlayersPrimaryKey,
			},
			Predicate: func(s *sql.Selector) {
				s.Where(sql.InValues(gameserver.PlayersPrimaryKey[1], fks...))
			},
			ScanValues: func() [2]interface{} {
				return [2]interface{}{new(sql.NullInt64), new(sql.NullInt64)}
			},
			Assign: func(out, in interface{}) error {
				eout, ok := out.(*sql.NullInt64)
				if !ok || eout == nil {
					return fmt.Errorf("unexpected id value for edge-out")
				}
				ein, ok := in.(*sql.NullInt64)
				if !ok || ein == nil {
					return fmt.Errorf("unexpected id value for edge-in")
				}
				outValue := int(eout.Int64)
				inValue := int(ein.Int64)
				node, ok := ids[outValue]
				if !ok {
					return fmt.Errorf("unexpected node id in edges: %v", outValue)
				}
				if _, ok := edges[inValue]; !ok {
					edgeids = append(edgeids, inValue)
				}
				edges[inValue] = append(edges[inValue], node)
				return nil
			},
		}
		if err := sqlgraph.QueryEdges(ctx, gsq.driver, _spec); err != nil {
			return nil, fmt.Errorf(`query edges "players": %w`, err)
		}
		query.Where(player.IDIn(edgeids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := edges[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected "players" node returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Players = append(nodes[i].Edges.Players, n)
			}
		}
	}

	return nodes, nil
}

func (gsq *GameServerQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := gsq.querySpec()
	if len(gsq.modifiers) > 0 {
		_spec.Modifiers = gsq.modifiers
	}
	return sqlgraph.CountNodes(ctx, gsq.driver, _spec)
}

func (gsq *GameServerQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := gsq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (gsq *GameServerQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   gameserver.Table,
			Columns: gameserver.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: gameserver.FieldID,
			},
		},
		From:   gsq.sql,
		Unique: true,
	}
	if unique := gsq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := gsq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gameserver.FieldID)
		for i := range fields {
			if fields[i] != gameserver.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := gsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := gsq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := gsq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := gsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (gsq *GameServerQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(gsq.driver.Dialect())
	t1 := builder.Table(gameserver.Table)
	columns := gsq.fields
	if len(columns) == 0 {
		columns = gameserver.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if gsq.sql != nil {
		selector = gsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, m := range gsq.modifiers {
		m(selector)
	}
	for _, p := range gsq.predicates {
		p(selector)
	}
	for _, p := range gsq.order {
		p(selector)
	}
	if offset := gsq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := gsq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (gsq *GameServerQuery) ForUpdate(opts ...sql.LockOption) *GameServerQuery {
	if gsq.driver.Dialect() == dialect.Postgres {
		gsq.Unique(false)
	}
	gsq.modifiers = append(gsq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return gsq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (gsq *GameServerQuery) ForShare(opts ...sql.LockOption) *GameServerQuery {
	if gsq.driver.Dialect() == dialect.Postgres {
		gsq.Unique(false)
	}
	gsq.modifiers = append(gsq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return gsq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (gsq *GameServerQuery) Modify(modifiers ...func(s *sql.Selector)) *GameServerSelect {
	gsq.modifiers = append(gsq.modifiers, modifiers...)
	return gsq.Select()
}

// GameServerGroupBy is the group-by builder for GameServer entities.
type GameServerGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (gsgb *GameServerGroupBy) Aggregate(fns ...AggregateFunc) *GameServerGroupBy {
	gsgb.fns = append(gsgb.fns, fns...)
	return gsgb
}

// Scan applies the group-by query and scans the result into the given value.
func (gsgb *GameServerGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := gsgb.path(ctx)
	if err != nil {
		return err
	}
	gsgb.sql = query
	return gsgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (gsgb *GameServerGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := gsgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (gsgb *GameServerGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(gsgb.fields) > 1 {
		return nil, errors.New("ent: GameServerGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := gsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (gsgb *GameServerGroupBy) StringsX(ctx context.Context) []string {
	v, err := gsgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (gsgb *GameServerGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = gsgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{gameserver.Label}
	default:
		err = fmt.Errorf("ent: GameServerGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (gsgb *GameServerGroupBy) StringX(ctx context.Context) string {
	v, err := gsgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (gsgb *GameServerGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(gsgb.fields) > 1 {
		return nil, errors.New("ent: GameServerGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := gsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (gsgb *GameServerGroupBy) IntsX(ctx context.Context) []int {
	v, err := gsgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (gsgb *GameServerGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = gsgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{gameserver.Label}
	default:
		err = fmt.Errorf("ent: GameServerGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (gsgb *GameServerGroupBy) IntX(ctx context.Context) int {
	v, err := gsgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (gsgb *GameServerGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(gsgb.fields) > 1 {
		return nil, errors.New("ent: GameServerGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := gsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (gsgb *GameServerGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := gsgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (gsgb *GameServerGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = gsgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{gameserver.Label}
	default:
		err = fmt.Errorf("ent: GameServerGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (gsgb *GameServerGroupBy) Float64X(ctx context.Context) float64 {
	v, err := gsgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (gsgb *GameServerGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(gsgb.fields) > 1 {
		return nil, errors.New("ent: GameServerGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := gsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (gsgb *GameServerGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := gsgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (gsgb *GameServerGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = gsgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{gameserver.Label}
	default:
		err = fmt.Errorf("ent: GameServerGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (gsgb *GameServerGroupBy) BoolX(ctx context.Context) bool {
	v, err := gsgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (gsgb *GameServerGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range gsgb.fields {
		if !gameserver.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := gsgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gsgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (gsgb *GameServerGroupBy) sqlQuery() *sql.Selector {
	selector := gsgb.sql.Select()
	aggregation := make([]string, 0, len(gsgb.fns))
	for _, fn := range gsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(gsgb.fields)+len(gsgb.fns))
		for _, f := range gsgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(gsgb.fields...)...)
}

// GameServerSelect is the builder for selecting fields of GameServer entities.
type GameServerSelect struct {
	*GameServerQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (gss *GameServerSelect) Scan(ctx context.Context, v interface{}) error {
	if err := gss.prepareQuery(ctx); err != nil {
		return err
	}
	gss.sql = gss.GameServerQuery.sqlQuery(ctx)
	return gss.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (gss *GameServerSelect) ScanX(ctx context.Context, v interface{}) {
	if err := gss.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (gss *GameServerSelect) Strings(ctx context.Context) ([]string, error) {
	if len(gss.fields) > 1 {
		return nil, errors.New("ent: GameServerSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := gss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (gss *GameServerSelect) StringsX(ctx context.Context) []string {
	v, err := gss.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (gss *GameServerSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = gss.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{gameserver.Label}
	default:
		err = fmt.Errorf("ent: GameServerSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (gss *GameServerSelect) StringX(ctx context.Context) string {
	v, err := gss.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (gss *GameServerSelect) Ints(ctx context.Context) ([]int, error) {
	if len(gss.fields) > 1 {
		return nil, errors.New("ent: GameServerSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := gss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (gss *GameServerSelect) IntsX(ctx context.Context) []int {
	v, err := gss.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (gss *GameServerSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = gss.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{gameserver.Label}
	default:
		err = fmt.Errorf("ent: GameServerSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (gss *GameServerSelect) IntX(ctx context.Context) int {
	v, err := gss.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (gss *GameServerSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(gss.fields) > 1 {
		return nil, errors.New("ent: GameServerSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := gss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (gss *GameServerSelect) Float64sX(ctx context.Context) []float64 {
	v, err := gss.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (gss *GameServerSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = gss.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{gameserver.Label}
	default:
		err = fmt.Errorf("ent: GameServerSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (gss *GameServerSelect) Float64X(ctx context.Context) float64 {
	v, err := gss.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (gss *GameServerSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(gss.fields) > 1 {
		return nil, errors.New("ent: GameServerSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := gss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (gss *GameServerSelect) BoolsX(ctx context.Context) []bool {
	v, err := gss.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (gss *GameServerSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = gss.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{gameserver.Label}
	default:
		err = fmt.Errorf("ent: GameServerSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (gss *GameServerSelect) BoolX(ctx context.Context) bool {
	v, err := gss.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (gss *GameServerSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := gss.sql.Query()
	if err := gss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (gss *GameServerSelect) Modify(modifiers ...func(s *sql.Selector)) *GameServerSelect {
	gss.modifiers = append(gss.modifiers, modifiers...)
	return gss
}
