// Code generated by entc, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/responserms/response/ent/schema"
	"github.com/responserms/response/internal/ent/deathcertificate"
	"github.com/responserms/response/internal/ent/deathcertifier"
	"github.com/responserms/response/internal/ent/deathmanner"
	"github.com/responserms/response/internal/ent/deathplace"
	"github.com/responserms/response/internal/ent/ethnicity"
	"github.com/responserms/response/internal/ent/gameserver"
	"github.com/responserms/response/internal/ent/metadata"
	"github.com/responserms/response/internal/ent/oauthconnection"
	"github.com/responserms/response/internal/ent/person"
	"github.com/responserms/response/internal/ent/player"
	"github.com/responserms/response/internal/ent/playeridentifier"
	"github.com/responserms/response/internal/ent/race"
	"github.com/responserms/response/internal/ent/session"
	"github.com/responserms/response/internal/ent/setting"
	"github.com/responserms/response/internal/ent/sex"
	"github.com/responserms/response/internal/ent/state"
	"github.com/responserms/response/internal/ent/user"
	"github.com/responserms/response/internal/ent/vehicle"
	"github.com/responserms/response/internal/ent/vehicleclass"
	"github.com/responserms/response/internal/ent/vehiclecolor"
	"github.com/responserms/response/internal/ent/vehiclemake"
	"github.com/responserms/response/internal/ent/vehiclemodel"
	"github.com/responserms/response/internal/ent/vehicleregistration"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	deathcertificateMixin := schema.DeathCertificate{}.Mixin()
	deathcertificateMixinHooks1 := deathcertificateMixin[1].Hooks()
	deathcertificate.Hooks[0] = deathcertificateMixinHooks1[0]
	deathcertificateMixinFields1 := deathcertificateMixin[1].Fields()
	_ = deathcertificateMixinFields1
	deathcertificateFields := schema.DeathCertificate{}.Fields()
	_ = deathcertificateFields
	// deathcertificateDescCreatedAt is the schema descriptor for created_at field.
	deathcertificateDescCreatedAt := deathcertificateMixinFields1[0].Descriptor()
	// deathcertificate.DefaultCreatedAt holds the default value on creation for the created_at field.
	deathcertificate.DefaultCreatedAt = deathcertificateDescCreatedAt.Default.(func() time.Time)
	// deathcertificateDescUpdatedAt is the schema descriptor for updated_at field.
	deathcertificateDescUpdatedAt := deathcertificateMixinFields1[3].Descriptor()
	// deathcertificate.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	deathcertificate.DefaultUpdatedAt = deathcertificateDescUpdatedAt.Default.(func() time.Time)
	// deathcertificate.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	deathcertificate.UpdateDefaultUpdatedAt = deathcertificateDescUpdatedAt.UpdateDefault.(func() time.Time)
	// deathcertificateDescRequiresCertification is the schema descriptor for requires_certification field.
	deathcertificateDescRequiresCertification := deathcertificateFields[4].Descriptor()
	// deathcertificate.DefaultRequiresCertification holds the default value on creation for the requires_certification field.
	deathcertificate.DefaultRequiresCertification = deathcertificateDescRequiresCertification.Default.(bool)
	deathcertifierMixin := schema.DeathCertifier{}.Mixin()
	deathcertifierMixinHooks1 := deathcertifierMixin[1].Hooks()
	deathcertifier.Hooks[0] = deathcertifierMixinHooks1[0]
	deathcertifierMixinFields1 := deathcertifierMixin[1].Fields()
	_ = deathcertifierMixinFields1
	deathcertifierMixinFields2 := deathcertifierMixin[2].Fields()
	_ = deathcertifierMixinFields2
	deathcertifierFields := schema.DeathCertifier{}.Fields()
	_ = deathcertifierFields
	// deathcertifierDescCreatedAt is the schema descriptor for created_at field.
	deathcertifierDescCreatedAt := deathcertifierMixinFields1[0].Descriptor()
	// deathcertifier.DefaultCreatedAt holds the default value on creation for the created_at field.
	deathcertifier.DefaultCreatedAt = deathcertifierDescCreatedAt.Default.(func() time.Time)
	// deathcertifierDescUpdatedAt is the schema descriptor for updated_at field.
	deathcertifierDescUpdatedAt := deathcertifierMixinFields1[3].Descriptor()
	// deathcertifier.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	deathcertifier.DefaultUpdatedAt = deathcertifierDescUpdatedAt.Default.(func() time.Time)
	// deathcertifier.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	deathcertifier.UpdateDefaultUpdatedAt = deathcertifierDescUpdatedAt.UpdateDefault.(func() time.Time)
	// deathcertifierDescShort is the schema descriptor for short field.
	deathcertifierDescShort := deathcertifierMixinFields2[0].Descriptor()
	// deathcertifier.ShortValidator is a validator for the "short" field. It is called by the builders before save.
	deathcertifier.ShortValidator = deathcertifierDescShort.Validators[0].(func(string) error)
	// deathcertifierDescTitle is the schema descriptor for title field.
	deathcertifierDescTitle := deathcertifierMixinFields2[1].Descriptor()
	// deathcertifier.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	deathcertifier.TitleValidator = deathcertifierDescTitle.Validators[0].(func(string) error)
	// deathcertifierDescDescription is the schema descriptor for description field.
	deathcertifierDescDescription := deathcertifierMixinFields2[2].Descriptor()
	// deathcertifier.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	deathcertifier.DescriptionValidator = deathcertifierDescDescription.Validators[0].(func(string) error)
	deathmannerMixin := schema.DeathManner{}.Mixin()
	deathmannerMixinHooks1 := deathmannerMixin[1].Hooks()
	deathmanner.Hooks[0] = deathmannerMixinHooks1[0]
	deathmannerMixinFields1 := deathmannerMixin[1].Fields()
	_ = deathmannerMixinFields1
	deathmannerMixinFields2 := deathmannerMixin[2].Fields()
	_ = deathmannerMixinFields2
	deathmannerFields := schema.DeathManner{}.Fields()
	_ = deathmannerFields
	// deathmannerDescCreatedAt is the schema descriptor for created_at field.
	deathmannerDescCreatedAt := deathmannerMixinFields1[0].Descriptor()
	// deathmanner.DefaultCreatedAt holds the default value on creation for the created_at field.
	deathmanner.DefaultCreatedAt = deathmannerDescCreatedAt.Default.(func() time.Time)
	// deathmannerDescUpdatedAt is the schema descriptor for updated_at field.
	deathmannerDescUpdatedAt := deathmannerMixinFields1[3].Descriptor()
	// deathmanner.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	deathmanner.DefaultUpdatedAt = deathmannerDescUpdatedAt.Default.(func() time.Time)
	// deathmanner.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	deathmanner.UpdateDefaultUpdatedAt = deathmannerDescUpdatedAt.UpdateDefault.(func() time.Time)
	// deathmannerDescShort is the schema descriptor for short field.
	deathmannerDescShort := deathmannerMixinFields2[0].Descriptor()
	// deathmanner.ShortValidator is a validator for the "short" field. It is called by the builders before save.
	deathmanner.ShortValidator = deathmannerDescShort.Validators[0].(func(string) error)
	// deathmannerDescTitle is the schema descriptor for title field.
	deathmannerDescTitle := deathmannerMixinFields2[1].Descriptor()
	// deathmanner.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	deathmanner.TitleValidator = deathmannerDescTitle.Validators[0].(func(string) error)
	// deathmannerDescDescription is the schema descriptor for description field.
	deathmannerDescDescription := deathmannerMixinFields2[2].Descriptor()
	// deathmanner.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	deathmanner.DescriptionValidator = deathmannerDescDescription.Validators[0].(func(string) error)
	deathplaceMixin := schema.DeathPlace{}.Mixin()
	deathplaceMixinHooks1 := deathplaceMixin[1].Hooks()
	deathplace.Hooks[0] = deathplaceMixinHooks1[0]
	deathplaceMixinFields1 := deathplaceMixin[1].Fields()
	_ = deathplaceMixinFields1
	deathplaceMixinFields2 := deathplaceMixin[2].Fields()
	_ = deathplaceMixinFields2
	deathplaceFields := schema.DeathPlace{}.Fields()
	_ = deathplaceFields
	// deathplaceDescCreatedAt is the schema descriptor for created_at field.
	deathplaceDescCreatedAt := deathplaceMixinFields1[0].Descriptor()
	// deathplace.DefaultCreatedAt holds the default value on creation for the created_at field.
	deathplace.DefaultCreatedAt = deathplaceDescCreatedAt.Default.(func() time.Time)
	// deathplaceDescUpdatedAt is the schema descriptor for updated_at field.
	deathplaceDescUpdatedAt := deathplaceMixinFields1[3].Descriptor()
	// deathplace.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	deathplace.DefaultUpdatedAt = deathplaceDescUpdatedAt.Default.(func() time.Time)
	// deathplace.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	deathplace.UpdateDefaultUpdatedAt = deathplaceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// deathplaceDescShort is the schema descriptor for short field.
	deathplaceDescShort := deathplaceMixinFields2[0].Descriptor()
	// deathplace.ShortValidator is a validator for the "short" field. It is called by the builders before save.
	deathplace.ShortValidator = deathplaceDescShort.Validators[0].(func(string) error)
	// deathplaceDescTitle is the schema descriptor for title field.
	deathplaceDescTitle := deathplaceMixinFields2[1].Descriptor()
	// deathplace.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	deathplace.TitleValidator = deathplaceDescTitle.Validators[0].(func(string) error)
	// deathplaceDescDescription is the schema descriptor for description field.
	deathplaceDescDescription := deathplaceMixinFields2[2].Descriptor()
	// deathplace.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	deathplace.DescriptionValidator = deathplaceDescDescription.Validators[0].(func(string) error)
	ethnicityMixin := schema.Ethnicity{}.Mixin()
	ethnicityMixinHooks1 := ethnicityMixin[1].Hooks()
	ethnicity.Hooks[0] = ethnicityMixinHooks1[0]
	ethnicityMixinFields1 := ethnicityMixin[1].Fields()
	_ = ethnicityMixinFields1
	ethnicityMixinFields2 := ethnicityMixin[2].Fields()
	_ = ethnicityMixinFields2
	ethnicityFields := schema.Ethnicity{}.Fields()
	_ = ethnicityFields
	// ethnicityDescCreatedAt is the schema descriptor for created_at field.
	ethnicityDescCreatedAt := ethnicityMixinFields1[0].Descriptor()
	// ethnicity.DefaultCreatedAt holds the default value on creation for the created_at field.
	ethnicity.DefaultCreatedAt = ethnicityDescCreatedAt.Default.(func() time.Time)
	// ethnicityDescUpdatedAt is the schema descriptor for updated_at field.
	ethnicityDescUpdatedAt := ethnicityMixinFields1[3].Descriptor()
	// ethnicity.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	ethnicity.DefaultUpdatedAt = ethnicityDescUpdatedAt.Default.(func() time.Time)
	// ethnicity.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	ethnicity.UpdateDefaultUpdatedAt = ethnicityDescUpdatedAt.UpdateDefault.(func() time.Time)
	// ethnicityDescShort is the schema descriptor for short field.
	ethnicityDescShort := ethnicityMixinFields2[0].Descriptor()
	// ethnicity.ShortValidator is a validator for the "short" field. It is called by the builders before save.
	ethnicity.ShortValidator = ethnicityDescShort.Validators[0].(func(string) error)
	// ethnicityDescTitle is the schema descriptor for title field.
	ethnicityDescTitle := ethnicityMixinFields2[1].Descriptor()
	// ethnicity.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	ethnicity.TitleValidator = ethnicityDescTitle.Validators[0].(func(string) error)
	// ethnicityDescDescription is the schema descriptor for description field.
	ethnicityDescDescription := ethnicityMixinFields2[2].Descriptor()
	// ethnicity.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	ethnicity.DescriptionValidator = ethnicityDescDescription.Validators[0].(func(string) error)
	gameserverMixin := schema.GameServer{}.Mixin()
	gameserverMixinHooks1 := gameserverMixin[1].Hooks()
	gameserver.Hooks[0] = gameserverMixinHooks1[0]
	gameserverMixinFields1 := gameserverMixin[1].Fields()
	_ = gameserverMixinFields1
	gameserverFields := schema.GameServer{}.Fields()
	_ = gameserverFields
	// gameserverDescCreatedAt is the schema descriptor for created_at field.
	gameserverDescCreatedAt := gameserverMixinFields1[0].Descriptor()
	// gameserver.DefaultCreatedAt holds the default value on creation for the created_at field.
	gameserver.DefaultCreatedAt = gameserverDescCreatedAt.Default.(func() time.Time)
	// gameserverDescUpdatedAt is the schema descriptor for updated_at field.
	gameserverDescUpdatedAt := gameserverMixinFields1[3].Descriptor()
	// gameserver.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	gameserver.DefaultUpdatedAt = gameserverDescUpdatedAt.Default.(func() time.Time)
	// gameserver.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	gameserver.UpdateDefaultUpdatedAt = gameserverDescUpdatedAt.UpdateDefault.(func() time.Time)
	// gameserverDescName is the schema descriptor for name field.
	gameserverDescName := gameserverFields[0].Descriptor()
	// gameserver.NameValidator is a validator for the "name" field. It is called by the builders before save.
	gameserver.NameValidator = gameserverDescName.Validators[0].(func(string) error)
	// gameserverDescMonitoring is the schema descriptor for monitoring field.
	gameserverDescMonitoring := gameserverFields[4].Descriptor()
	// gameserver.DefaultMonitoring holds the default value on creation for the monitoring field.
	gameserver.DefaultMonitoring = gameserverDescMonitoring.Default.(bool)
	metadataMixin := schema.Metadata{}.Mixin()
	metadataMixinHooks1 := metadataMixin[1].Hooks()
	metadata.Hooks[0] = metadataMixinHooks1[0]
	metadataMixinFields1 := metadataMixin[1].Fields()
	_ = metadataMixinFields1
	metadataFields := schema.Metadata{}.Fields()
	_ = metadataFields
	// metadataDescCreatedAt is the schema descriptor for created_at field.
	metadataDescCreatedAt := metadataMixinFields1[0].Descriptor()
	// metadata.DefaultCreatedAt holds the default value on creation for the created_at field.
	metadata.DefaultCreatedAt = metadataDescCreatedAt.Default.(func() time.Time)
	// metadataDescUpdatedAt is the schema descriptor for updated_at field.
	metadataDescUpdatedAt := metadataMixinFields1[3].Descriptor()
	// metadata.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	metadata.DefaultUpdatedAt = metadataDescUpdatedAt.Default.(func() time.Time)
	// metadata.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	metadata.UpdateDefaultUpdatedAt = metadataDescUpdatedAt.UpdateDefault.(func() time.Time)
	oauthconnectionMixin := schema.OAuthConnection{}.Mixin()
	oauthconnectionMixinHooks1 := oauthconnectionMixin[1].Hooks()
	oauthconnection.Hooks[0] = oauthconnectionMixinHooks1[0]
	oauthconnectionMixinFields1 := oauthconnectionMixin[1].Fields()
	_ = oauthconnectionMixinFields1
	oauthconnectionFields := schema.OAuthConnection{}.Fields()
	_ = oauthconnectionFields
	// oauthconnectionDescCreatedAt is the schema descriptor for created_at field.
	oauthconnectionDescCreatedAt := oauthconnectionMixinFields1[0].Descriptor()
	// oauthconnection.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthconnection.DefaultCreatedAt = oauthconnectionDescCreatedAt.Default.(func() time.Time)
	// oauthconnectionDescUpdatedAt is the schema descriptor for updated_at field.
	oauthconnectionDescUpdatedAt := oauthconnectionMixinFields1[3].Descriptor()
	// oauthconnection.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oauthconnection.DefaultUpdatedAt = oauthconnectionDescUpdatedAt.Default.(func() time.Time)
	// oauthconnection.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oauthconnection.UpdateDefaultUpdatedAt = oauthconnectionDescUpdatedAt.UpdateDefault.(func() time.Time)
	personMixin := schema.Person{}.Mixin()
	personMixinHooks1 := personMixin[1].Hooks()
	person.Hooks[0] = personMixinHooks1[0]
	personMixinFields1 := personMixin[1].Fields()
	_ = personMixinFields1
	personFields := schema.Person{}.Fields()
	_ = personFields
	// personDescCreatedAt is the schema descriptor for created_at field.
	personDescCreatedAt := personMixinFields1[0].Descriptor()
	// person.DefaultCreatedAt holds the default value on creation for the created_at field.
	person.DefaultCreatedAt = personDescCreatedAt.Default.(func() time.Time)
	// personDescUpdatedAt is the schema descriptor for updated_at field.
	personDescUpdatedAt := personMixinFields1[3].Descriptor()
	// person.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	person.DefaultUpdatedAt = personDescUpdatedAt.Default.(func() time.Time)
	// person.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	person.UpdateDefaultUpdatedAt = personDescUpdatedAt.UpdateDefault.(func() time.Time)
	playerMixin := schema.Player{}.Mixin()
	playerMixinHooks1 := playerMixin[1].Hooks()
	player.Hooks[0] = playerMixinHooks1[0]
	playerMixinFields1 := playerMixin[1].Fields()
	_ = playerMixinFields1
	playerFields := schema.Player{}.Fields()
	_ = playerFields
	// playerDescCreatedAt is the schema descriptor for created_at field.
	playerDescCreatedAt := playerMixinFields1[0].Descriptor()
	// player.DefaultCreatedAt holds the default value on creation for the created_at field.
	player.DefaultCreatedAt = playerDescCreatedAt.Default.(func() time.Time)
	// playerDescUpdatedAt is the schema descriptor for updated_at field.
	playerDescUpdatedAt := playerMixinFields1[3].Descriptor()
	// player.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	player.DefaultUpdatedAt = playerDescUpdatedAt.Default.(func() time.Time)
	// player.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	player.UpdateDefaultUpdatedAt = playerDescUpdatedAt.UpdateDefault.(func() time.Time)
	playeridentifierMixin := schema.PlayerIdentifier{}.Mixin()
	playeridentifierMixinHooks1 := playeridentifierMixin[1].Hooks()
	playeridentifier.Hooks[0] = playeridentifierMixinHooks1[0]
	playeridentifierMixinFields1 := playeridentifierMixin[1].Fields()
	_ = playeridentifierMixinFields1
	playeridentifierFields := schema.PlayerIdentifier{}.Fields()
	_ = playeridentifierFields
	// playeridentifierDescCreatedAt is the schema descriptor for created_at field.
	playeridentifierDescCreatedAt := playeridentifierMixinFields1[0].Descriptor()
	// playeridentifier.DefaultCreatedAt holds the default value on creation for the created_at field.
	playeridentifier.DefaultCreatedAt = playeridentifierDescCreatedAt.Default.(func() time.Time)
	// playeridentifierDescUpdatedAt is the schema descriptor for updated_at field.
	playeridentifierDescUpdatedAt := playeridentifierMixinFields1[3].Descriptor()
	// playeridentifier.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	playeridentifier.DefaultUpdatedAt = playeridentifierDescUpdatedAt.Default.(func() time.Time)
	// playeridentifier.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	playeridentifier.UpdateDefaultUpdatedAt = playeridentifierDescUpdatedAt.UpdateDefault.(func() time.Time)
	// playeridentifierDescValue is the schema descriptor for value field.
	playeridentifierDescValue := playeridentifierFields[0].Descriptor()
	// playeridentifier.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	playeridentifier.ValueValidator = playeridentifierDescValue.Validators[0].(func(string) error)
	raceMixin := schema.Race{}.Mixin()
	raceMixinHooks1 := raceMixin[1].Hooks()
	race.Hooks[0] = raceMixinHooks1[0]
	raceMixinFields1 := raceMixin[1].Fields()
	_ = raceMixinFields1
	raceMixinFields2 := raceMixin[2].Fields()
	_ = raceMixinFields2
	raceFields := schema.Race{}.Fields()
	_ = raceFields
	// raceDescCreatedAt is the schema descriptor for created_at field.
	raceDescCreatedAt := raceMixinFields1[0].Descriptor()
	// race.DefaultCreatedAt holds the default value on creation for the created_at field.
	race.DefaultCreatedAt = raceDescCreatedAt.Default.(func() time.Time)
	// raceDescUpdatedAt is the schema descriptor for updated_at field.
	raceDescUpdatedAt := raceMixinFields1[3].Descriptor()
	// race.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	race.DefaultUpdatedAt = raceDescUpdatedAt.Default.(func() time.Time)
	// race.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	race.UpdateDefaultUpdatedAt = raceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// raceDescShort is the schema descriptor for short field.
	raceDescShort := raceMixinFields2[0].Descriptor()
	// race.ShortValidator is a validator for the "short" field. It is called by the builders before save.
	race.ShortValidator = raceDescShort.Validators[0].(func(string) error)
	// raceDescTitle is the schema descriptor for title field.
	raceDescTitle := raceMixinFields2[1].Descriptor()
	// race.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	race.TitleValidator = raceDescTitle.Validators[0].(func(string) error)
	// raceDescDescription is the schema descriptor for description field.
	raceDescDescription := raceMixinFields2[2].Descriptor()
	// race.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	race.DescriptionValidator = raceDescDescription.Validators[0].(func(string) error)
	sessionMixin := schema.Session{}.Mixin()
	sessionMixinHooks1 := sessionMixin[1].Hooks()
	session.Hooks[0] = sessionMixinHooks1[0]
	sessionMixinFields1 := sessionMixin[1].Fields()
	_ = sessionMixinFields1
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionMixinFields1[0].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	// sessionDescUpdatedAt is the schema descriptor for updated_at field.
	sessionDescUpdatedAt := sessionMixinFields1[3].Descriptor()
	// session.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	session.DefaultUpdatedAt = sessionDescUpdatedAt.Default.(func() time.Time)
	// session.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	session.UpdateDefaultUpdatedAt = sessionDescUpdatedAt.UpdateDefault.(func() time.Time)
	settingMixin := schema.Setting{}.Mixin()
	settingMixinHooks1 := settingMixin[1].Hooks()
	setting.Hooks[0] = settingMixinHooks1[0]
	settingMixinFields1 := settingMixin[1].Fields()
	_ = settingMixinFields1
	settingFields := schema.Setting{}.Fields()
	_ = settingFields
	// settingDescCreatedAt is the schema descriptor for created_at field.
	settingDescCreatedAt := settingMixinFields1[0].Descriptor()
	// setting.DefaultCreatedAt holds the default value on creation for the created_at field.
	setting.DefaultCreatedAt = settingDescCreatedAt.Default.(func() time.Time)
	// settingDescUpdatedAt is the schema descriptor for updated_at field.
	settingDescUpdatedAt := settingMixinFields1[3].Descriptor()
	// setting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	setting.DefaultUpdatedAt = settingDescUpdatedAt.Default.(func() time.Time)
	// setting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	setting.UpdateDefaultUpdatedAt = settingDescUpdatedAt.UpdateDefault.(func() time.Time)
	sexMixin := schema.Sex{}.Mixin()
	sexMixinHooks1 := sexMixin[1].Hooks()
	sex.Hooks[0] = sexMixinHooks1[0]
	sexMixinFields1 := sexMixin[1].Fields()
	_ = sexMixinFields1
	sexMixinFields2 := sexMixin[2].Fields()
	_ = sexMixinFields2
	sexFields := schema.Sex{}.Fields()
	_ = sexFields
	// sexDescCreatedAt is the schema descriptor for created_at field.
	sexDescCreatedAt := sexMixinFields1[0].Descriptor()
	// sex.DefaultCreatedAt holds the default value on creation for the created_at field.
	sex.DefaultCreatedAt = sexDescCreatedAt.Default.(func() time.Time)
	// sexDescUpdatedAt is the schema descriptor for updated_at field.
	sexDescUpdatedAt := sexMixinFields1[3].Descriptor()
	// sex.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	sex.DefaultUpdatedAt = sexDescUpdatedAt.Default.(func() time.Time)
	// sex.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	sex.UpdateDefaultUpdatedAt = sexDescUpdatedAt.UpdateDefault.(func() time.Time)
	// sexDescShort is the schema descriptor for short field.
	sexDescShort := sexMixinFields2[0].Descriptor()
	// sex.ShortValidator is a validator for the "short" field. It is called by the builders before save.
	sex.ShortValidator = sexDescShort.Validators[0].(func(string) error)
	// sexDescTitle is the schema descriptor for title field.
	sexDescTitle := sexMixinFields2[1].Descriptor()
	// sex.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	sex.TitleValidator = sexDescTitle.Validators[0].(func(string) error)
	// sexDescDescription is the schema descriptor for description field.
	sexDescDescription := sexMixinFields2[2].Descriptor()
	// sex.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	sex.DescriptionValidator = sexDescDescription.Validators[0].(func(string) error)
	stateMixin := schema.State{}.Mixin()
	stateMixinHooks1 := stateMixin[1].Hooks()
	state.Hooks[0] = stateMixinHooks1[0]
	stateMixinFields1 := stateMixin[1].Fields()
	_ = stateMixinFields1
	stateMixinFields2 := stateMixin[2].Fields()
	_ = stateMixinFields2
	stateFields := schema.State{}.Fields()
	_ = stateFields
	// stateDescCreatedAt is the schema descriptor for created_at field.
	stateDescCreatedAt := stateMixinFields1[0].Descriptor()
	// state.DefaultCreatedAt holds the default value on creation for the created_at field.
	state.DefaultCreatedAt = stateDescCreatedAt.Default.(func() time.Time)
	// stateDescUpdatedAt is the schema descriptor for updated_at field.
	stateDescUpdatedAt := stateMixinFields1[3].Descriptor()
	// state.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	state.DefaultUpdatedAt = stateDescUpdatedAt.Default.(func() time.Time)
	// state.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	state.UpdateDefaultUpdatedAt = stateDescUpdatedAt.UpdateDefault.(func() time.Time)
	// stateDescShort is the schema descriptor for short field.
	stateDescShort := stateMixinFields2[0].Descriptor()
	// state.ShortValidator is a validator for the "short" field. It is called by the builders before save.
	state.ShortValidator = stateDescShort.Validators[0].(func(string) error)
	// stateDescTitle is the schema descriptor for title field.
	stateDescTitle := stateMixinFields2[1].Descriptor()
	// state.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	state.TitleValidator = stateDescTitle.Validators[0].(func(string) error)
	// stateDescDescription is the schema descriptor for description field.
	stateDescDescription := stateMixinFields2[2].Descriptor()
	// state.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	state.DescriptionValidator = stateDescDescription.Validators[0].(func(string) error)
	userMixin := schema.User{}.Mixin()
	userMixinHooks1 := userMixin[1].Hooks()
	user.Hooks[0] = userMixinHooks1[0]
	userMixinFields1 := userMixin[1].Fields()
	_ = userMixinFields1
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields1[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields1[3].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[2].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	vehicleMixin := schema.Vehicle{}.Mixin()
	vehicleMixinHooks1 := vehicleMixin[1].Hooks()
	vehicle.Hooks[0] = vehicleMixinHooks1[0]
	vehicleMixinFields1 := vehicleMixin[1].Fields()
	_ = vehicleMixinFields1
	vehicleFields := schema.Vehicle{}.Fields()
	_ = vehicleFields
	// vehicleDescCreatedAt is the schema descriptor for created_at field.
	vehicleDescCreatedAt := vehicleMixinFields1[0].Descriptor()
	// vehicle.DefaultCreatedAt holds the default value on creation for the created_at field.
	vehicle.DefaultCreatedAt = vehicleDescCreatedAt.Default.(func() time.Time)
	// vehicleDescUpdatedAt is the schema descriptor for updated_at field.
	vehicleDescUpdatedAt := vehicleMixinFields1[3].Descriptor()
	// vehicle.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	vehicle.DefaultUpdatedAt = vehicleDescUpdatedAt.Default.(func() time.Time)
	// vehicle.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	vehicle.UpdateDefaultUpdatedAt = vehicleDescUpdatedAt.UpdateDefault.(func() time.Time)
	vehicleclassMixin := schema.VehicleClass{}.Mixin()
	vehicleclassMixinHooks1 := vehicleclassMixin[1].Hooks()
	vehicleclass.Hooks[0] = vehicleclassMixinHooks1[0]
	vehicleclassMixinFields1 := vehicleclassMixin[1].Fields()
	_ = vehicleclassMixinFields1
	vehicleclassMixinFields2 := vehicleclassMixin[2].Fields()
	_ = vehicleclassMixinFields2
	vehicleclassFields := schema.VehicleClass{}.Fields()
	_ = vehicleclassFields
	// vehicleclassDescCreatedAt is the schema descriptor for created_at field.
	vehicleclassDescCreatedAt := vehicleclassMixinFields1[0].Descriptor()
	// vehicleclass.DefaultCreatedAt holds the default value on creation for the created_at field.
	vehicleclass.DefaultCreatedAt = vehicleclassDescCreatedAt.Default.(func() time.Time)
	// vehicleclassDescUpdatedAt is the schema descriptor for updated_at field.
	vehicleclassDescUpdatedAt := vehicleclassMixinFields1[3].Descriptor()
	// vehicleclass.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	vehicleclass.DefaultUpdatedAt = vehicleclassDescUpdatedAt.Default.(func() time.Time)
	// vehicleclass.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	vehicleclass.UpdateDefaultUpdatedAt = vehicleclassDescUpdatedAt.UpdateDefault.(func() time.Time)
	// vehicleclassDescShort is the schema descriptor for short field.
	vehicleclassDescShort := vehicleclassMixinFields2[0].Descriptor()
	// vehicleclass.ShortValidator is a validator for the "short" field. It is called by the builders before save.
	vehicleclass.ShortValidator = vehicleclassDescShort.Validators[0].(func(string) error)
	// vehicleclassDescTitle is the schema descriptor for title field.
	vehicleclassDescTitle := vehicleclassMixinFields2[1].Descriptor()
	// vehicleclass.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	vehicleclass.TitleValidator = vehicleclassDescTitle.Validators[0].(func(string) error)
	// vehicleclassDescDescription is the schema descriptor for description field.
	vehicleclassDescDescription := vehicleclassMixinFields2[2].Descriptor()
	// vehicleclass.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	vehicleclass.DescriptionValidator = vehicleclassDescDescription.Validators[0].(func(string) error)
	vehiclecolorMixin := schema.VehicleColor{}.Mixin()
	vehiclecolorMixinHooks1 := vehiclecolorMixin[1].Hooks()
	vehiclecolor.Hooks[0] = vehiclecolorMixinHooks1[0]
	vehiclecolorMixinFields1 := vehiclecolorMixin[1].Fields()
	_ = vehiclecolorMixinFields1
	vehiclecolorMixinFields2 := vehiclecolorMixin[2].Fields()
	_ = vehiclecolorMixinFields2
	vehiclecolorFields := schema.VehicleColor{}.Fields()
	_ = vehiclecolorFields
	// vehiclecolorDescCreatedAt is the schema descriptor for created_at field.
	vehiclecolorDescCreatedAt := vehiclecolorMixinFields1[0].Descriptor()
	// vehiclecolor.DefaultCreatedAt holds the default value on creation for the created_at field.
	vehiclecolor.DefaultCreatedAt = vehiclecolorDescCreatedAt.Default.(func() time.Time)
	// vehiclecolorDescUpdatedAt is the schema descriptor for updated_at field.
	vehiclecolorDescUpdatedAt := vehiclecolorMixinFields1[3].Descriptor()
	// vehiclecolor.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	vehiclecolor.DefaultUpdatedAt = vehiclecolorDescUpdatedAt.Default.(func() time.Time)
	// vehiclecolor.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	vehiclecolor.UpdateDefaultUpdatedAt = vehiclecolorDescUpdatedAt.UpdateDefault.(func() time.Time)
	// vehiclecolorDescShort is the schema descriptor for short field.
	vehiclecolorDescShort := vehiclecolorMixinFields2[0].Descriptor()
	// vehiclecolor.ShortValidator is a validator for the "short" field. It is called by the builders before save.
	vehiclecolor.ShortValidator = vehiclecolorDescShort.Validators[0].(func(string) error)
	// vehiclecolorDescTitle is the schema descriptor for title field.
	vehiclecolorDescTitle := vehiclecolorMixinFields2[1].Descriptor()
	// vehiclecolor.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	vehiclecolor.TitleValidator = vehiclecolorDescTitle.Validators[0].(func(string) error)
	// vehiclecolorDescDescription is the schema descriptor for description field.
	vehiclecolorDescDescription := vehiclecolorMixinFields2[2].Descriptor()
	// vehiclecolor.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	vehiclecolor.DescriptionValidator = vehiclecolorDescDescription.Validators[0].(func(string) error)
	vehiclemakeMixin := schema.VehicleMake{}.Mixin()
	vehiclemakeMixinHooks1 := vehiclemakeMixin[1].Hooks()
	vehiclemake.Hooks[0] = vehiclemakeMixinHooks1[0]
	vehiclemakeMixinFields1 := vehiclemakeMixin[1].Fields()
	_ = vehiclemakeMixinFields1
	vehiclemakeMixinFields2 := vehiclemakeMixin[2].Fields()
	_ = vehiclemakeMixinFields2
	vehiclemakeFields := schema.VehicleMake{}.Fields()
	_ = vehiclemakeFields
	// vehiclemakeDescCreatedAt is the schema descriptor for created_at field.
	vehiclemakeDescCreatedAt := vehiclemakeMixinFields1[0].Descriptor()
	// vehiclemake.DefaultCreatedAt holds the default value on creation for the created_at field.
	vehiclemake.DefaultCreatedAt = vehiclemakeDescCreatedAt.Default.(func() time.Time)
	// vehiclemakeDescUpdatedAt is the schema descriptor for updated_at field.
	vehiclemakeDescUpdatedAt := vehiclemakeMixinFields1[3].Descriptor()
	// vehiclemake.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	vehiclemake.DefaultUpdatedAt = vehiclemakeDescUpdatedAt.Default.(func() time.Time)
	// vehiclemake.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	vehiclemake.UpdateDefaultUpdatedAt = vehiclemakeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// vehiclemakeDescShort is the schema descriptor for short field.
	vehiclemakeDescShort := vehiclemakeMixinFields2[0].Descriptor()
	// vehiclemake.ShortValidator is a validator for the "short" field. It is called by the builders before save.
	vehiclemake.ShortValidator = vehiclemakeDescShort.Validators[0].(func(string) error)
	// vehiclemakeDescTitle is the schema descriptor for title field.
	vehiclemakeDescTitle := vehiclemakeMixinFields2[1].Descriptor()
	// vehiclemake.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	vehiclemake.TitleValidator = vehiclemakeDescTitle.Validators[0].(func(string) error)
	// vehiclemakeDescDescription is the schema descriptor for description field.
	vehiclemakeDescDescription := vehiclemakeMixinFields2[2].Descriptor()
	// vehiclemake.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	vehiclemake.DescriptionValidator = vehiclemakeDescDescription.Validators[0].(func(string) error)
	vehiclemodelMixin := schema.VehicleModel{}.Mixin()
	vehiclemodelMixinHooks1 := vehiclemodelMixin[1].Hooks()
	vehiclemodel.Hooks[0] = vehiclemodelMixinHooks1[0]
	vehiclemodelMixinFields1 := vehiclemodelMixin[1].Fields()
	_ = vehiclemodelMixinFields1
	vehiclemodelMixinFields2 := vehiclemodelMixin[2].Fields()
	_ = vehiclemodelMixinFields2
	vehiclemodelFields := schema.VehicleModel{}.Fields()
	_ = vehiclemodelFields
	// vehiclemodelDescCreatedAt is the schema descriptor for created_at field.
	vehiclemodelDescCreatedAt := vehiclemodelMixinFields1[0].Descriptor()
	// vehiclemodel.DefaultCreatedAt holds the default value on creation for the created_at field.
	vehiclemodel.DefaultCreatedAt = vehiclemodelDescCreatedAt.Default.(func() time.Time)
	// vehiclemodelDescUpdatedAt is the schema descriptor for updated_at field.
	vehiclemodelDescUpdatedAt := vehiclemodelMixinFields1[3].Descriptor()
	// vehiclemodel.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	vehiclemodel.DefaultUpdatedAt = vehiclemodelDescUpdatedAt.Default.(func() time.Time)
	// vehiclemodel.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	vehiclemodel.UpdateDefaultUpdatedAt = vehiclemodelDescUpdatedAt.UpdateDefault.(func() time.Time)
	// vehiclemodelDescShort is the schema descriptor for short field.
	vehiclemodelDescShort := vehiclemodelMixinFields2[0].Descriptor()
	// vehiclemodel.ShortValidator is a validator for the "short" field. It is called by the builders before save.
	vehiclemodel.ShortValidator = vehiclemodelDescShort.Validators[0].(func(string) error)
	// vehiclemodelDescTitle is the schema descriptor for title field.
	vehiclemodelDescTitle := vehiclemodelMixinFields2[1].Descriptor()
	// vehiclemodel.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	vehiclemodel.TitleValidator = vehiclemodelDescTitle.Validators[0].(func(string) error)
	// vehiclemodelDescDescription is the schema descriptor for description field.
	vehiclemodelDescDescription := vehiclemodelMixinFields2[2].Descriptor()
	// vehiclemodel.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	vehiclemodel.DescriptionValidator = vehiclemodelDescDescription.Validators[0].(func(string) error)
	vehicleregistrationMixin := schema.VehicleRegistration{}.Mixin()
	vehicleregistrationMixinHooks1 := vehicleregistrationMixin[1].Hooks()
	vehicleregistration.Hooks[0] = vehicleregistrationMixinHooks1[0]
	vehicleregistrationMixinFields1 := vehicleregistrationMixin[1].Fields()
	_ = vehicleregistrationMixinFields1
	vehicleregistrationFields := schema.VehicleRegistration{}.Fields()
	_ = vehicleregistrationFields
	// vehicleregistrationDescCreatedAt is the schema descriptor for created_at field.
	vehicleregistrationDescCreatedAt := vehicleregistrationMixinFields1[0].Descriptor()
	// vehicleregistration.DefaultCreatedAt holds the default value on creation for the created_at field.
	vehicleregistration.DefaultCreatedAt = vehicleregistrationDescCreatedAt.Default.(func() time.Time)
	// vehicleregistrationDescUpdatedAt is the schema descriptor for updated_at field.
	vehicleregistrationDescUpdatedAt := vehicleregistrationMixinFields1[3].Descriptor()
	// vehicleregistration.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	vehicleregistration.DefaultUpdatedAt = vehicleregistrationDescUpdatedAt.Default.(func() time.Time)
	// vehicleregistration.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	vehicleregistration.UpdateDefaultUpdatedAt = vehicleregistrationDescUpdatedAt.UpdateDefault.(func() time.Time)
}

const (
	Version = "(devel)" // Version of ent codegen.
)
